# Bluetooth keyboard name
CONFIG_ZMK_KEYBOARD_NAME="Chocofi"

# Increase Bluetooth TX power for better range
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# Enable USB output
CONFIG_ZMK_USB=y

# Enable Bluetooth
CONFIG_ZMK_BLE=y
CONFIG_BT=y

# BLE connection stability
CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y
CONFIG_BT_CTLR_PHY_2M=n